name: Code Style Check

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        id: prettier
        run: |
          result=$(npx prettier --check .)
          if [ $? -ne 0 ]; then
            echo "Prettier found code style issues. Please run 'npx prettier --write .' locally to fix them."
            exit 1
          fi

      - name: Run ESLint
        if: |
          steps.prettier.outcome == 'success' &&
          github.event_name == 'pull_request' &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true
        run: |
          npx eslint . --format=html --output-file eslint-report.html

      - name: Upload ESLint Report
        if: |
          steps.prettier.outcome == 'success' &&
          github.event_name == 'pull_request' &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.html
